# Generated by Django 6.1 on 2026-09-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=120, verbose_name='Nombre Completo')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono / Celular')),
                ('ciudad', models.CharField(max_length=80, verbose_name='Ciudad')),
                ('empresa_dependencia', models.CharField(max_length=100, verbose_name='Empresa o Dependencia')),
                ('tipo_contacto', models.CharField(choices=[('Personal', 'Personal'), ('Laboral', 'Laboral'), ('Académico', 'Académico'), ('Institucional', 'Institucional')], default='Personal', max_length=20, verbose_name='Tipo de Contacto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
