# Generated by Django 6.1 on 2026-09-05 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='nombre_completo',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='El nombre no puede contener números.', regex='^[^0-9]*$')], verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede contener números.', regex='^[0-9]+$')], verbose_name='Teléfono / Celular'),
        ),
    ]
